import type { Metadata } from 'next';
import '@inkonchain/ink-kit/style.css';
import { Navbar } from '@/components/Navbar';

import './globals.css';
import { Providers } from './providers';

export const metadata: Metadata = {
  title: 'Kraken New Wallet',
  description: 'Generated by dkrabdev',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="ink:dark-theme">
      <body>
        <Providers>
          <div>
            <Navbar />
            <div className="flex h-[calc(100vh-95px)] ink:bg-background-light">
              <div className="flex-1">{children}</div>
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
